version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '05:00'
      timezone: 'Europe/Madrid'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    reviewers:
      - 'Sumolari'
    assignees:
      - 'Sumolari'
    versioning-strategy: increase
    labels:
      - 'dependencies'
    rebase-strategy: 'auto'
