name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn --frozen-lockfile
      - run: |
          yarn all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Install git
        run: |
          sudo apt-get update 
          sudo apt-get install -y git
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Upload coverage
        uses: caffco/code-climate-github-action@v0.0.1-alpha.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          repository_root_path: ${{github.workspace}}
          collect_coverage: 'true'
          coverage_file_patterns: |
            coverage/lcov.info:lcov
