name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn --frozen-lockfile
      - run: |
          yarn all
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install git
        run: |
          sudo apt-get update 
          sudo apt-get install -y git
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run unit tests
        run: yarn test
      - name: Upload coverage
        uses: caffco/code-climate-github-action@v0.0.1-alpha.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          repository_root_path: ${{github.workspace}}
          collect_coverage: 'true'
          coverage_file_patterns: |
            coverage/lcov.info:lcov
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install git
        run: |
          sudo apt-get update 
          sudo apt-get install -y git
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Clear dependencies
        run: rm -rf node_modules
      - name: Run integration tests
        uses: ./
        with:
          base_branch: origin/main
